let myDate =new Date()
console.log(myDate.toString())
console.log(myDate.toDateString())
console.log(myDate.toLocaleDateString())
console.log(myDate.toLocaleString())
console.log(myDate.toTimeString())
console.log(myDate.toJSON())
console.log("*************************************")
let myCreatedDate=new Date(2023,0,26)
console.log(myCreatedDate.toDateString())
console.log(myCreatedDate.toLocaleString())
let myDate2=new Date("01-14-2023")
console.log(myDate2.toLocaleString())
console.log(myDate2.toDateString())
console.log("********************************")
let myTimeStamp=Date.now()
console.log(myTimeStamp)
console.log(Math.floor(Date.now()/1000))

let newDate=new Date
newDate.toLocaleString('default',{weekday:"long"})
console.log(newDate)